import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <title>Crack.Run</title>
        <meta
          name="FC온라인 구단주 전적검색"
          content="FC온라인 정보의 모든 것!! Crack.Run"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
