import type { Metadata } from "next";
import { Inter, Black_Han_Sans } from "next/font/google";
import "./globals.css";
import Footer from "./Footer";

// font
const cls = (...classnames: string[]) => classnames.join(" ");

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--inter",
});
const black_Han_Sans = Black_Han_Sans({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--black_Han_Sans",
});

export const FontClassNames = cls(inter.variable, black_Han_Sans.variable);

// meta
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <title>Crack.Run</title>
        <meta
          name="FC온라인 구단주 전적검색"
          content="FC온라인 정보의 모든 것!! Crack.Run"
        />
      </head>
      <body className={FontClassNames}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
